---
name: Build

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: 💾 Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: 🪝 Cache pre-commit hooks
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: "pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml')
            }}"

      - name: 🛠️ Install tools
        shell: bash
        run: |
          python3 -m pip install pre-commit platformio

      - name: 🏗️ Build firmware
        run: platformio run -e STM32F103RET6_sovol_maple

      - name: 📦 Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "firmware-${{ github.sha }}.zip"
          path: |
            .pio/build/STM32F103RET6_sovol_maple/*.bin

      - name: 🚢 Publish release artifacts
        if: github.event_name == 'release' && github.event.action == 'created'
        run: |
          cp .pio/build/STM32F103RET6_sovol_maple/*.bin "firmware-${{ github.ref_name }}.bin"
          gh release upload "${{ github.ref_name }}" "firmware-${{ github.ref_name }}.bin"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
