---
name: Build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: 💾 Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: 🪝 Cache pre-commit hooks
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: "pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml')
            }}"

      - name: 🛠️ Install tools
        shell: bash
        run: |
          python3 -m pip install pre-commit platformio

      - name: 🏗️ Build firmware
        run: platformio run -e STM32F103RET6_sovol_maple
        working-directory: ./MarlinSV06Plus

      - name: 📦 Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "firmware-${{ github.sha }}.zip"
          path: |
            MarlinSV06Plus/.pio/build/STM32F103RET6_sovol_maple/*.bin

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
